# Generated by Django 5.0 on 2023-12-22 23:42
import BookingManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('image', models.ImageField(
                    upload_to=BookingManagement.models.image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
