# Generated by Django 5.0 on 2024-01-15 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingManagement', '0002_create_booking_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('entrance', models.DateTimeField()),
                ('exit', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingManagement.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingManagement.room')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
