# Generated by Django 4.2.6 on 2023-10-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entarance', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'booking',
                'ordering': ['id', 'entarance', 'departure', 'creationDate', 'updateDate', 'price'],
            },
        ),
    ]
