# Generated by Django 4.2.6 on 2023-10-23 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingManagement', '0002_create_room_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingManagement.room')),
            ],
        ),
    ]
